<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_B.ComCA</name>
   <tag></tag>
   <elementGuidId>ab2d2951-6e71-4dd0-a84c-1edc805c2e14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3027']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3027 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;B.Com[CA] ►&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1661385a-485f-411f-be7a-58460b60f6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>48a5107e-17a8-4b38-94fa-a9930f14bd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>B.Com[CA]</value>
      <webElementGuid>ecd14355-c0e8-404d-b0e9-e3a9f3f7483f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3027&quot;)/a[1]</value>
      <webElementGuid>14c8c123-9b4b-4544-8444-954434bc5a21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3027']/a</value>
      <webElementGuid>4fb4588e-0091-4dce-a701-741a3e87b026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'B.Com[CA]')]</value>
      <webElementGuid>c9db798b-9296-41ba-8771-5c2f459f7f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='National Seminar/Conference/Workshop'])[2]/following::a[1]</value>
      <webElementGuid>5885a0d0-7dad-4440-a1c8-9f518b5f72ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multimedia'])[1]/following::a[2]</value>
      <webElementGuid>1d17a029-150d-4bed-b667-bc9ca1259f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[5]/preceding::a[1]</value>
      <webElementGuid>3723c03e-e8fd-4a3a-8ca7-a48ddaeae1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curriculum'])[5]/preceding::a[2]</value>
      <webElementGuid>4a51e28f-d538-45f9-bb82-c545579dec49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='B.Com[CA]']/parent::*</value>
      <webElementGuid>6b8eadf4-0bb6-49f1-badd-ab1110d5c484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[17]</value>
      <webElementGuid>f28a62e4-346f-4e62-b0fb-959cc69207b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/ul/li[4]/ul/li[5]/a</value>
      <webElementGuid>06847125-e296-4718-9e0c-31c810c3b1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'B.Com[CA]' or . = 'B.Com[CA]')]</value>
      <webElementGuid>428ad1fc-82f5-4557-8fa3-f951b7335be0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
