<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BBA</name>
   <tag></tag>
   <elementGuidId>54166c6b-efa1-4bc8-bd26-4222300e32cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-636']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-636 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;BBA&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>960101bc-98b3-4466-8c7c-6efe6ecd0dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BBA</value>
      <webElementGuid>80f3ea48-2855-430e-bfc2-11d7e92469d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-636&quot;)/a[1]</value>
      <webElementGuid>6852fc63-f853-4d11-8ef2-fd93ebb29113</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-636']/a</value>
      <webElementGuid>55768e27-8b8c-4e38-9e6e-db6222f38615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BBA')]</value>
      <webElementGuid>578aac45-81d8-4bc5-a16d-e26ce3ab11d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='National Seminar/Conference/Workshop'])[1]/following::a[1]</value>
      <webElementGuid>5cb6c437-a10f-4377-a63b-cad7c85c3c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pollution'])[1]/following::a[2]</value>
      <webElementGuid>2b8d5f55-1d7f-41d7-b706-41454e1bcf28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[3]/preceding::a[1]</value>
      <webElementGuid>43ca7771-f548-4763-acc0-66dd269a1148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curriculum'])[3]/preceding::a[2]</value>
      <webElementGuid>863ba430-04a8-4cd0-813c-2d451768b2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BBA']/parent::*</value>
      <webElementGuid>51446106-ee12-432d-89b0-cf89945ae78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/ul/li[4]/ul/li[3]/a</value>
      <webElementGuid>27c30942-f141-4a42-8cb7-0001135deb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'BBA' or . = 'BBA')]</value>
      <webElementGuid>04cc0e57-238c-41dc-a560-d15c99510eec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
