<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Driving</name>
   <tag></tag>
   <elementGuidId>0e7f4d48-97c0-4c16-8cb7-43e33c87cfdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-6996']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-6996 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Driving&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c3c458c-4df0-433c-84e5-8796d08b403d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nmssvcollege.com/special-features/driving/</value>
      <webElementGuid>13f63f76-e7db-4db7-82e9-b0ba7a850be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Driving</value>
      <webElementGuid>b492ef32-6da8-49ab-a7b5-8dea57e443dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-6996&quot;)/a[1]</value>
      <webElementGuid>2492d272-cfa2-46f7-a9e9-891f851a9192</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-6996']/a</value>
      <webElementGuid>ddb75e6b-92bd-4b64-9cc1-abaee5366401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Driving')]</value>
      <webElementGuid>13a6f680-9467-4c36-ae5f-3ab3cd0aeee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitness Centre'])[1]/following::a[1]</value>
      <webElementGuid>058ed840-5740-4587-a61e-fe818e55c909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coaching for Competitive Exams'])[1]/following::a[2]</value>
      <webElementGuid>fa28544b-09d8-40bb-89c5-ae334f828e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fly over Transition Course'])[1]/preceding::a[1]</value>
      <webElementGuid>014af18f-81b8-4a9f-80c8-4c5d889a1e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Coaching classes for Slow Learners'])[1]/preceding::a[2]</value>
      <webElementGuid>6a420d77-ec24-46b1-ab84-7b3026bdf9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Driving']/parent::*</value>
      <webElementGuid>8d86ae8d-5224-445a-9955-b79b680822a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nmssvcollege.com/special-features/driving/')]</value>
      <webElementGuid>ffdabbc5-764a-4b35-b21b-2d3de55885c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[7]/a</value>
      <webElementGuid>c9491b1b-61ed-4131-8182-545a9507b2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nmssvcollege.com/special-features/driving/' and (text() = 'Driving' or . = 'Driving')]</value>
      <webElementGuid>acb1cd3b-3bc3-4427-b4a8-1ee8528c4870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
