<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fine Arts</name>
   <tag></tag>
   <elementGuidId>b3fd067e-012c-4387-85d6-87227bb5d3e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-6986']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-6986 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Fine Arts ►&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6ffb9632-1ef4-4758-ba8c-80d6980d0caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://#</value>
      <webElementGuid>83cfb061-c377-4cfe-b9ef-89505406cb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fine Arts</value>
      <webElementGuid>5728f2ff-3c5d-43fa-ad2a-7ed629dc608d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-6986&quot;)/a[1]</value>
      <webElementGuid>0b3c25d0-7006-42de-a224-274ce2e6b33d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-6986']/a</value>
      <webElementGuid>1543710e-04f8-4b4d-b55e-262ded061be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Fine Arts')]</value>
      <webElementGuid>95a40f39-3998-4cb0-96db-381cd72be8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YRC'])[1]/following::a[1]</value>
      <webElementGuid>7cfa7f58-6ac3-44f6-87b5-4aa4c54c7a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RRC'])[1]/following::a[2]</value>
      <webElementGuid>c6a1675a-e8ab-491e-9687-99b58cfa06e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Youth Welfare Club'])[1]/preceding::a[1]</value>
      <webElementGuid>0a4209d6-2d15-4aac-9843-2fb17e7e3d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Value Education Center'])[1]/preceding::a[3]</value>
      <webElementGuid>bd4e7c21-f65b-4dd0-8f0b-58b6e5e732af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fine Arts']/parent::*</value>
      <webElementGuid>d08a68b1-ab59-40d7-a366-f0c90462de0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://#'])[4]</value>
      <webElementGuid>a2a0f5e5-a3f8-4d82-802f-6367ff8a9eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[3]/a</value>
      <webElementGuid>dde53267-86f6-4703-9a97-4e5588204e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://#' and (text() = 'Fine Arts' or . = 'Fine Arts')]</value>
      <webElementGuid>9623e940-1a22-4ee3-9eb5-e80e6087296a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
