<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Organogram</name>
   <tag></tag>
   <elementGuidId>dcd1c976-da47-4221-bcb5-2cb6aedcf242</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-6898']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-6898 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Organogram&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f2c93514-9790-44b2-a6c4-4ffb3c125db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8da247ac-f829-43d1-8aa8-44f462e550df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nmssvcollege.com/wp-content/uploads/2022/11/6.2.2.-Chart.pdf</value>
      <webElementGuid>ca9c7eb3-f17a-4700-89e1-bc7f194f1053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Organogram</value>
      <webElementGuid>88c02134-f971-43ee-86fd-563bae7a47c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-6898&quot;)/a[1]</value>
      <webElementGuid>7f1914f4-9794-427e-a43a-39b298cf51e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-6898']/a</value>
      <webElementGuid>d7196949-52bf-460b-914f-e7ae57ad3259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Organogram')]</value>
      <webElementGuid>625a293e-babb-4f7e-b030-3c6e15e3b297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vision &amp; Mission'])[1]/following::a[1]</value>
      <webElementGuid>756d1b0c-b2bf-4e14-9628-eb1073987daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About N.M.S.S.V.C'])[1]/following::a[2]</value>
      <webElementGuid>bfdbf92b-03c7-4079-a1b1-cd6777970058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code of Conduct'])[1]/preceding::a[1]</value>
      <webElementGuid>904a4036-c95f-4764-a2b2-d50feb9a032e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activities'])[2]/preceding::a[5]</value>
      <webElementGuid>f2382763-23a1-416d-bad2-8ee638dd753f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Organogram']/parent::*</value>
      <webElementGuid>1dee6ef7-f3c9-4b3f-bfb7-c77c73c22450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nmssvcollege.com/wp-content/uploads/2022/11/6.2.2.-Chart.pdf')]</value>
      <webElementGuid>340091a4-1fad-4e45-ac79-b935327b21c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/ul/li[3]/a</value>
      <webElementGuid>46531251-dd3e-4e25-bebd-a0b5229318b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nmssvcollege.com/wp-content/uploads/2022/11/6.2.2.-Chart.pdf' and (text() = 'Organogram' or . = 'Organogram')]</value>
      <webElementGuid>a201a027-8228-47a7-adbb-7ea49de3c000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
