<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_RRC</name>
   <tag></tag>
   <elementGuidId>61d76721-f219-4dab-9713-096bde49bf8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-6984']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-6984 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#menu-item-6984 >> internal:role=link[name=&quot;RRC&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b1c1e667-09e6-455c-8d7b-8e299f0530e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nmssvcollege.com/rrc/</value>
      <webElementGuid>96d87201-a22a-4906-b455-0074148adb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RRC</value>
      <webElementGuid>bc01d0e4-af1f-4488-94a1-fe5657ea2a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-6984&quot;)/a[1]</value>
      <webElementGuid>416e02a2-5055-4cf2-b3cb-4211551a9466</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-6984']/a</value>
      <webElementGuid>453241a8-4b81-4bb4-b3f7-93b52363fd92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'RRC')]</value>
      <webElementGuid>76bfba00-284f-483c-816d-7dea63f1736d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NCC'])[1]/following::a[1]</value>
      <webElementGuid>45de7263-79b7-4cd0-98c0-5074ec464139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NSS'])[1]/following::a[2]</value>
      <webElementGuid>71d054e1-9a55-4a90-aacf-757d7c44ec7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YRC'])[1]/preceding::a[1]</value>
      <webElementGuid>da4bc59f-a39b-45df-a50f-9e0e9ac99aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fine Arts'])[1]/preceding::a[2]</value>
      <webElementGuid>f3eebb76-8083-457b-8f74-68736c0ea866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RRC']/parent::*</value>
      <webElementGuid>21f7fb3f-2375-47b2-8f21-46cfc2c0695e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nmssvcollege.com/rrc/')]</value>
      <webElementGuid>64e5479e-85b6-4652-8f24-2c9d7b64e4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/ul/li[3]/a</value>
      <webElementGuid>6dc35879-053f-4cd5-a897-0484493f9c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nmssvcollege.com/rrc/' and (text() = 'RRC' or . = 'RRC')]</value>
      <webElementGuid>4b84416f-4a25-48ed-9bde-f7df197a3089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
