<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vision  Mission_1</name>
   <tag></tag>
   <elementGuidId>038d5b3c-d2f5-474f-bf8c-b9a1da3b7b07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-2507']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-2507 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#menu-item-2507 >> internal:role=link[name=&quot;Vision &amp; Mission&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1bd5cc26-d336-4950-a55f-eb9fefc3b99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nmssvcollege.com/iqac-visionmission/</value>
      <webElementGuid>ee919bb7-2b30-49ba-9017-a725da590843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vision &amp; Mission</value>
      <webElementGuid>44378b59-57b8-4cc9-b8c1-fa0929527fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-2507&quot;)/a[1]</value>
      <webElementGuid>cd789d11-d0fa-4b26-97a0-52e24a806495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-2507']/a</value>
      <webElementGuid>bb16d09c-dd04-4d4f-b94e-38afc74a9c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Vision &amp; Mission')])[2]</value>
      <webElementGuid>0cf0b1c6-ecee-471e-90a2-667a4ec00d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IQAC'])[1]/following::a[1]</value>
      <webElementGuid>cbba2f38-530d-4dc5-9cc9-9cf47c91ffaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Admission'])[1]/following::a[2]</value>
      <webElementGuid>70729ec5-fa7c-49b0-862a-759d4c4dcc45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Objectives'])[1]/preceding::a[1]</value>
      <webElementGuid>d719e3cb-e3d3-4056-b7f9-b95990dac498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Functions'])[1]/preceding::a[2]</value>
      <webElementGuid>ea07d662-c77a-4f00-a207-6fd0ad3ba893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nmssvcollege.com/iqac-visionmission/')]</value>
      <webElementGuid>02f1e4c0-8cae-4652-a84a-ac53d9358c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/a</value>
      <webElementGuid>5570b1a7-5571-47cb-af38-b5797f7ac50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nmssvcollege.com/iqac-visionmission/' and (text() = 'Vision &amp; Mission' or . = 'Vision &amp; Mission')]</value>
      <webElementGuid>c8d25be1-ce94-4eb4-8c4d-fdf249906209</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
