<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_YRC</name>
   <tag></tag>
   <elementGuidId>bddf2cab-42bb-40dd-a670-3882cb18ca57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-6985']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-6985 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#menu-item-6985 >> internal:role=link[name=&quot;YRC&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a44c7a3f-47d2-4b8b-b193-51305f652968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nmssvcollege.com/yrc/</value>
      <webElementGuid>60984ef6-d8a1-44e0-a7a8-a960bfcb08b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YRC</value>
      <webElementGuid>0bf93dbe-5685-4e25-8a9b-cd43e52f55f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-6985&quot;)/a[1]</value>
      <webElementGuid>0ef4e597-c517-49d7-88ba-136467c05816</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-6985']/a</value>
      <webElementGuid>7c66c8e7-52ae-43ea-87fc-17c7a90276c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'YRC')]</value>
      <webElementGuid>475caa22-164d-4e0f-9a41-111e8bf0333c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RRC'])[1]/following::a[1]</value>
      <webElementGuid>04c9c727-c3fa-464c-bcd9-328b0806cbff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NCC'])[1]/following::a[2]</value>
      <webElementGuid>d2d9d07c-0e82-4b29-b831-b1415dd1cecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fine Arts'])[1]/preceding::a[1]</value>
      <webElementGuid>04fad192-2e96-4b89-913d-928db93f55a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Youth Welfare Club'])[1]/preceding::a[2]</value>
      <webElementGuid>5d4b5292-a98a-4356-b75b-e48b5320951e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='YRC']/parent::*</value>
      <webElementGuid>df4d9d8c-3b52-4fec-93bd-ef2fbd0f507c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nmssvcollege.com/yrc/')]</value>
      <webElementGuid>c55bfb1b-a011-4cdf-babf-b9c7e63550ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/ul/li[4]/a</value>
      <webElementGuid>36c222cf-1637-4e49-aece-842882029e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nmssvcollege.com/yrc/' and (text() = 'YRC' or . = 'YRC')]</value>
      <webElementGuid>c5022c32-679c-4803-b218-6a1fc440f5b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
